### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError:<exception str() failed>

### ISSUE THREAD

**Issue by wodezhongguoxin** [charlesq34/pointnet2#100]
When I compiled the script "tf_sampling_compile.sh", there was no errors. But when I ran the python file "tf_sampling.py", I got an error just like the title. The detailed error message is showed below. I have no idea how to solve it. Any advice will be appreciated.

Traceback (most recent call last):
  File "tf_sampling.py", line 13, in <module>
    sampling_module=tf.load_op_library(os.path.join(BASE_DIR, 'tf_sampling_so.so'))
  File "/home/weiyu/.local/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: <exception str() failed>

**Comment by nuosferatu** [comment]
我也遇到了和你完全一样的问题，请问你解决了吗？

**Comment by wodezhongguoxin** [comment]
> 我也遇到了和你完全一样的问题，请问你解决了吗？

Bro, I have successfully solved it. The reason for the problem is that your own tensorflow path is not  corresponds to the path in tf_sampling_compile.sh. You need to modify  the path in tf_sampling_compile.sh at  your situation. Be sure to all the path in tf_sampling_compile.sh are right. Have a good luck. By the way, How do you know I'm a Chinese?

**Comment by nuosferatu** [comment]
> > 我也遇到了和你完全一样的问题，请问你解决了吗？
> 
> Bro, I have successfully solved it. The reason for the problem is that your own tensorflow path is not corresponds to the path in tf_sampling_compile.sh. You need to modify the path in tf_sampling_compile.sh at your situation. Be sure to all the path in tf_sampling_compile.sh are right. Have a good luck. By the way, How do you know I'm a Chinese?

thank you, i'll try to fix it as you said. By the way, because you id: wodezhongguoxin.

**Comment by purity77** [comment]
秀呀

**Comment by wodezhongguoxin** [comment]
朋友，你好。>O< ------------------ 原始邮件 ------------------
发件人: "purity77"<notifications@github.com>
发送时间: 2019年6月8日(星期六) 下午5:43
收件人: "charlesq34/pointnet2"<pointnet2@noreply.github.com>;
抄送: "wodezhongguoxin"<2584755727@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [charlesq34/pointnet2]tensorflow.python.framework.errors_impl.NotFoundError:<exception str() failed>(#100)



秀呀
 
&mdash;

**Comment by emtelGNR** [comment]
hi,I just met the same problem with you,but my tensorflow path is  corresponds to the path in tf_sampling_compile.sh. Can you help me? thanks a lot.
![2019-11-08 19-49-11屏幕截图](https://user-images.githubusercontent.com/48984931/68474713-225fac00-0261-11ea-8d6d-91508a771f52.png)

**Comment by emtelGNR** [comment]
![2019-11-08 19-49-11屏幕截图](https://user-images.githubusercontent.com/48984931/68474748-40c5a780-0261-11ea-8ed8-e0e448bd2f08.png)

**Comment by emtelGNR** [comment]
![2019-11-08 19-49-11屏幕截图](https://user-images.githubusercontent.com/48984931/68474785-5b981c00-0261-11ea-8ba9-488277e48ac3.png)
