### ISSUE TITLE
Errors while running part_seg/train.py

### ISSUE THREAD

**Issue by thirdlastletter** [charlesq34/pointnet2#127]
Hi,

I`ve been getting the following errors while trying to run python train.py in for the part segmentation. I compiled the tf_ops so I'm not sure where the errors come from.

`Traceback (most recent call last):
  File "train.py", line 57, in <module>
    MODEL = importlib.import_module(FLAGS.model) # import network module
  File "/home/user/anaconda2/envs/TFGPU/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/pointnet2/models/pointnet2_sem_seg.py", line 9, in <module>
    from pointnet_util import pointnet_sa_module, pointnet_fp_module
  File "/home/user/pointnet2/utils/pointnet_util.py", line 15, in <module>
    from tf_sampling import farthest_point_sample, gather_point
  File "/home/user/pointnet2/tf_ops/sampling/tf_sampling.py", line 12, in <module>
    sampling_module=tf.load_op_library(os.path.join(BASE_DIR, 'tf_sampling_so.so'))
  File "/home/user/anaconda2/envs/TFGPU/lib/python3.7/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/user/pointnet2/tf_ops/sampling/tf_sampling_so.so: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrESs
`

Has anyone had this problem before?

**Comment by QinjieXiao** [comment]
I got the same problem too.
