### ISSUE TITLE
When I running "pyhton train.py ", we will meet a mistake  "AttributeError: module 'provider' has no attribute 'rotate_point_cloud'"

### ISSUE THREAD

**Issue by Allan-Xu** [charlesq34/pointnet2#161]
This is my mistake , I hope someone can help me solve it.
`(pcc) allan@allan:~/Allan/pointnet2-master$ python train.py 
pid: 6083
WARNING:tensorflow:From /home/allan/anaconda3/envs/pcc/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From /home/allan/Allan/pointnet2-master/utils/pointnet_util.py:127: calling reduce_max_v1 (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From /home/allan/Allan/pointnet2-master/utils/tf_util.py:613: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
WARNING:tensorflow:From train.py:129: to_int64 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
--- Get training operator
WARNING:tensorflow:From /home/allan/anaconda3/envs/pcc/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From /home/allan/anaconda3/envs/pcc/lib/python3.6/site-packages/tensorflow/python/ops/math_grad.py:102: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
2019-11-01 21:06:46.056311: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-11-01 21:06:46.086952: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2494240000 Hz
2019-11-01 21:06:46.088411: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55ac67eeab60 executing computations on platform Host. Devices:
2019-11-01 21:06:46.088454: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-11-01 21:06:46.191659: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:03:00.0
totalMemory: 10.92GiB freeMemory: 10.60GiB
2019-11-01 21:06:46.191705: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-11-01 21:06:46.193978: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-11-01 21:06:46.194001: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-11-01 21:06:46.194012: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-11-01 21:06:46.194104: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10311 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:03:00.0, compute capability: 6.1)
2019-11-01 21:06:46.196157: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55ac68678220 executing computations on platform CUDA. Devices:
2019-11-01 21:06:46.196180: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce GTX 1080 Ti, Compute Capability 6.1
**** EPOCH 000 ****
2019-11-01 21:06:47.811492
Traceback (most recent call last):
  File "train.py", line 284, in <module>
    train()
  File "train.py", line 177, in train
    train_one_epoch(sess, ops, train_writer)
  File "train.py", line 201, in train_one_epoch
    batch_data, batch_label = TRAIN_DATASET.next_batch(augment=True)
  File "/home/allan/Allan/pointnet2-master/modelnet_h5_dataset.py", line 117, in next_batch
    if augment: data_batch = self._augment_batch_data(data_batch)
  File "/home/allan/Allan/pointnet2-master/modelnet_h5_dataset.py", line 73, in _augment_batch_data
    rotated_data = provider.rotate_point_cloud(batch_data)
### AttributeError: module 'provider' has no attribute 'rotate_point_cloud'
`

**Comment by gefeiwang** [comment]
@Allan-Xu I met the same problem, because I have installed another package also called "provider". Changing the filename of utils/provider.py works for me.
