### ISSUE TITLE
 problems running in google colab, don't know what it can be

### ISSUE THREAD

**Issue by p4mela-g** [charlesq34/pointnet2#175]
Made the change from python2 to python3, but the code is ok.
Someone knows how to fix it?

mv: target 'Drive/pointnet2-master/data' is not a directory
Traceback (most recent call last):
  File "train.py", line 52, in <module>
    MODEL = importlib.import_module(FLAGS.model) # import network module
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/content/drive/My Drive/pointnet2-master/models/pointnet2_cls_ssg.py", line 13, in <module>
    from pointnet_util import pointnet_sa_module
  File "/content/drive/My Drive/pointnet2-master/utils/pointnet_util.py", line 15, in <module>
    from tf_sampling import farthest_point_sample, gather_point
  File "/content/drive/My Drive/pointnet2-master/tf_ops/sampling/tf_sampling.py", line 12, in <module>
    sampling_module=tf.load_op_library(os.path.join(BASE_DIR, 'tf_sampling_so.so'))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: libcudart.so.9.0: cannot open shared object file: No such file or directory

**Comment by syenpark** [comment]
DId you compile your own customized TF operators on Colab? When I did from the last week, they (Google colab) use `libcudart.so.10` something not `libcudart.so.9.0`.

**Comment by p4mela-g** [comment]
thanks for the reply, but i left it aside
