### ISSUE TITLE
AttributeError: module '5fa89fc3154996733eabb433e18fa62f' has no attribute 'farthest_point_sample'

### ISSUE THREAD

**Issue by vistar-terry** [charlesq34/pointnet2#200]
Hello,
When i run train, i got this error.
I have searched it on google, but got nothing.
Plesae help me, thank you.

Traceback (most recent call last):
  File "train_multi_gpu_one_hot.py", line 410, in <module>
    train()
  File "train_multi_gpu_one_hot.py", line 166, in train
    MODEL.get_model(pointclouds_pl, cls_labels_pl, is_training_pl, bn_decay=bn_decay)
  File "/home/thz/vistar/LSANet/models/dgs_part_seg_one_hot.py", line 28, in get_model
    group_all=False, is_training=is_training, bn_decay=bn_decay, scope='layer1')
  File "/home/thz/vistar/LSANet/utils/pointnet_util.py", line 209, in LSA_layer
    use_edge_feature=True)
  File "/home/thz/vistar/LSANet/utils/pointnet_util.py", line 37, in sample_and_group
    new_xyz = gather_point(xyz, farthest_point_sample(npoint, xyz))  # (batch_size, npoint, 3)
  File "/home/thz/vistar/LSANet/tf_ops/sampling/tf_sampling.py", line 56, in farthest_point_sample
    return sampling_module.farthest_point_sample(inp, npoint)
AttributeError: module '5fa89fc3154996733eabb433e18fa62f' has no attribute 'farthest_point_sample'

**Comment by lyy-1997-hub** [comment]
I have encountered that, you open the terminal and enter nvidia-smi to see if the graphics card driver is still there.Maybe you will find that graphics card driver is lost.

**Comment by qiminchen** [comment]
hi, I also ran into this problem, did you solve the problem? thanks

**Comment by lyy-1997-hub** [comment]
Yeah,I have solved it. But after such a long time,I don't remember the reason,sorry.



发自我的iPhone


------------------ Original ------------------
From: Qimin Chen ***@***.***&gt;
Date: Tue,May 4,2021 11:05 AM
To: charlesq34/pointnet2 ***@***.***&gt;
Cc: 李滢滢 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [charlesq34/pointnet2] AttributeError: module '5fa89fc3154996733eabb433e18fa62f' has no attribute 'farthest_point_sample' (#200)





 
hi, I also ran into this problem, did you solve the problem? thanks
