### ISSUE TITLE
/pointnet2/tf_ops/3d_interpolation/tf_interpolate_so.so: undefined symbol: _ZN10tensorflow15OpKernelContext21CtxFailureWithWarningENS_6StatusE

### ISSUE THREAD

**Issue by monjoybme** [charlesq34/pointnet2#205]
Dear All,
I am able to execute `tf_sampling_compile.sh` and `tf_grouping_compile.sh` successfully. But when I am executing `tf_interpolate_compile.sh`, I am getting an error message as `tf_interpolate.cpp:6:42: fatal error: tensorflow/core/framework/op.h: No such file or directory #include "tensorflow/core/framework/op.h"^
compilation terminated.
`
Code in `tf_interpolate_compile.sh` is `g++ -std=c++11 tf_interpolate.cpp -o tf_interpolate_so.so -shared -fPIC -I /usr/local/lib/python3.6/site-packages/tensorflow/include -I /usr/local/cuda-9.0/include -I /usr/local/lib/python3.6/site-packages/tensorflow/include/external/nsync/public -lcudart -L /usr/local/cuda-9.0/lib64/ -L/usr/local/lib/python3.6/site-packages/tensorflow -ltensorflow_framework -O2 -D_GLIBCXX_USE_CXX11_ABI=0

`

Below is the result of `train.py`
`Traceback (most recent call last):
  File "train.py", line 52, in <module>
    MODEL = importlib.import_module(FLAGS.model) # import network module
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pointnet2/models/pointnet2_cls_ssg.py", line 13, in <module>
    from pointnet_util import pointnet_sa_module
  File "/home/pointnet2/utils/pointnet_util.py", line 17, in <module>
    from tf_interpolate import three_nn, three_interpolate
  File "/home/pointnet2/tf_ops/3d_interpolation/tf_interpolate.py", line 7, in <module>
    interpolate_module=tf.load_op_library(os.path.join(BASE_DIR, 'tf_interpolate_so.so'))
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 60, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/pointnet2/tf_ops/3d_interpolation/tf_interpolate_so.so: undefined symbol: _ZN10tensorflow15OpKernelContext21CtxFailureWithWarningENS_6StatusE`

Any help will be highly appreciated. I am using tensorflow 1.2 and CUDA 9.0.

**Comment by monjoybme** [comment]
Solved this issue. I was using SCL environment for Python. I forgot to activate the environment. Now no issue.
