### ISSUE TITLE
TypeError: ('Keyword argument not understood:', 'decay')

### ISSUE THREAD

**Issue by iamancythomas** [charlesq34/pointnet2#242]
Im using tensorflow 2.3.0 and keras 2.3.0 version. What could be the solution for the error mentioned below :+1: 

 python train.py 
2022-08-08 12:23:16.539563: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2022-08-08 12:23:21.853660: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
pid: 4898
Traceback (most recent call last):
  File "train.py", line 284, in <module>
    train()
  File "train.py", line 121, in train
    pred, end_points = MODEL.get_model(pointclouds_pl, is_training_pl, bn_decay=bn_decay)
  File "/home/ancy/Desktop/IIITB/TERMII/PC-Algorithmns/pointnet2/pointnet2-master/models/pointnet2_cls_ssg.py", line 32, in get_model
    l1_xyz, l1_points, l1_indices = pointnet_sa_module(l0_xyz, l0_points, npoint=512, radius=0.2, nsample=32, mlp=[64,64,128], mlp2=None, group_all=False, is_training=is_training, bn_decay=bn_decay, scope='layer1', use_nchw=True)
  File "/home/ancy/Desktop/IIITB/TERMII/PC-Algorithmns/pointnet2/pointnet2-master/utils/pointnet_util.py", line 122, in pointnet_sa_module
    data_format=data_format) 
  File "/home/ancy/Desktop/IIITB/TERMII/PC-Algorithmns/pointnet2/pointnet2-master/utils/tf_util.py", line 181, in conv2d
    data_format=data_format)
  File "/home/ancy/Desktop/IIITB/TERMII/PC-Algorithmns/pointnet2/pointnet2-master/utils/tf_util.py", line 577, in batch_norm_for_conv2d
    return batch_norm_template(inputs, is_training, scope, [0,1,2], bn_decay, data_format)
  File "/home/ancy/Desktop/IIITB/TERMII/PC-Algorithmns/pointnet2/pointnet2-master/utils/tf_util.py", line 532, in batch_norm_template
    data_format=data_format)
  File "/home/ancy/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/layers/normalization.py", line 174, in __init__
    super(BatchNormalizationBase, self).__init__(name=name, **kwargs)
  File "/home/ancy/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/ancy/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer_v1.py", line 165, in __init__
    generic_utils.validate_kwargs(kwargs, allowed_kwargs)
  File "/home/ancy/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 778, in validate_kwargs
    raise TypeError(error_message, kwarg)
TypeError: ('Keyword argument not understood:', 'decay')

Thanks.
Ancy

**Comment by iamancythomas** [comment]
Can someone respond to my query please. Could not solve yet.
