### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by lucheng07082221** [charlesq34/pointnet2#25]
when i run python part_seg/train.py, then take this error:

2018-03-08 13:39:33.715566: W tensorflow/core/common_runtime/bfc_allocator.cc:277] ****************************************************************************************************
2018-03-08 13:39:33.715579: W tensorflow/core/framework/op_kernel.cc:1158] Resource exhausted: OOM when allocating tensor with shape[32,2048,128]
Traceback (most recent call last):
  File "/home/lc/Downloads/pointnet2/part_seg/train.py", line 322, in <module>
    train()
  File "/home/lc/Downloads/pointnet2/part_seg/train.py", line 160, in train
    train_one_epoch(sess, ops, train_writer)
  File "/home/lc/Downloads/pointnet2/part_seg/train.py", line 205, in train_one_epoch
    ops['train_op'], ops['loss'], ops['pred']], feed_dict=feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[32,2048,128]
	 [[Node: dp1/cond/dropout/mul = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](dp1/cond/dropout/div, dp1/cond/dropout/Floor)]]
	 [[Node: gradients/fa_layer3/conv_1/Conv2D_grad/tuple/control_dependency_1/_547 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_3391_gradients/fa_layer3/conv_1/Conv2D_grad/tuple/control_dependency_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op u'dp1/cond/dropout/mul', defined at:
  File "/home/lc/Downloads/pointnet2/part_seg/train.py", line 322, in <module>
    train()
  File "/home/lc/Downloads/pointnet2/part_seg/train.py", line 108, in train
    pred, end_points = MODEL.get_model(pointclouds_pl, is_training_pl, bn_decay=bn_decay)
  File "/home/lc/Downloads/pointnet2/models/pointnet2_part_seg.py", line 38, in get_model
    net = tf_util.dropout(net, keep_prob=0.5, is_training=is_training, scope='dp1')
  File "/home/lc/Downloads/pointnet2/utils/tf_util.py", line 614, in dropout
    lambda: inputs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 289, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 1814, in cond
    orig_res_t, res_t = context_t.BuildCondBranch(true_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 1689, in BuildCondBranch
    original_result = fn()
  File "/home/lc/Downloads/pointnet2/utils/tf_util.py", line 613, in <lambda>
    lambda: tf.nn.dropout(inputs, keep_prob, noise_shape),
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 1915, in dropout
    ret = math_ops.div(x, keep_prob) * binary_tensor
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 838, in binary_op_wrapper
    return func(x, y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 1061, in _mul_dispatch
    return gen_math_ops._mul(x, y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 1377, in _mul
    result = _op_def_lib.apply_op("Mul", x=x, y=y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[32,2048,128]
	 [[Node: dp1/cond/dropout/mul = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](dp1/cond/dropout/div, dp1/cond/dropout/Floor)]]
	 [[Node: gradients/fa_layer3/conv_1/Conv2D_grad/tuple/control_dependency_1/_547 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_3391_gradients/fa_layer3/conv_1/Conv2D_grad/tuple/control_dependency_1", tensor_type=DT_FLOAT, _device="/

can you help me?

**Comment by salehjg** [comment]
have you tried to reduce batch size?
looks like it is 32
