### ISSUE TITLE
Problems with object part segmentation

### ISSUE THREAD

**Issue by l53ma** [charlesq34/pointnet2#40]
Thanks for sharing your great work!

I am a beginner of deep learning models used on point clouds. I am very interested about your achievement. I can successfully conducted classification operation using your codes. However, I have one question when conducting object part segmentation operation on ShapeNetPart dataset. 

After running "cd part_seg", and  "python train.py", it output an Error message as following:

Traceback (most recent call last):
File "train.py", line 47, in <module>
    MODEL = importlib.import_module(FLAGS.model) # import network module
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named model

My operating environment is Ubuntu16.04 + python2.7, can you help me address this issue?

Thank you for your kind assistance.

**Comment by OmarAhmadien** [comment]
@mf27 I tried what you said and I got this error:
`File "train.py", line 48, in <module>

    MODEL = importlib.import_module(FLAGS.model) # import network module

`  File "/XXX/miniconda3/envs/tensorflow/lib/python2.7/importlib/__init__.py", line 37, in import_module
__import__(name)
`

`ImportError: No module named pointnet2_sem_seg`
