### ISSUE TITLE
scannet no provider with attr rotate_point_cloud_z

### ISSUE THREAD

**Issue by rnunziata** [charlesq34/pointnet2#58]
```
**** EPOCH 000 ****
2018-08-12 21:10:32.686332
Traceback (most recent call last):
  File "train.py", line 440, in <module>
    train()
  File "train.py", line 175, in train
    train_one_epoch(sess, ops, train_writer)
  File "train.py", line 238, in train_one_epoch
    aug_data = provider.rotate_point_cloud_z(batch_data)
AttributeError: 'module' object has no attribute 'rotate_point_cloud_z'
```

using:  what model should be used?

`parser.add_argument('--model', default='pointnet2_sem_seg', help='Model name [default: pointnet2_sem_seg]')`

**Comment by ZGX010** [comment]
I also face that,can you help me？

**Comment by rnunziata** [comment]
take a look at :https://github.com/charlesq34/pointnet2/blob/master/utils/provider.py
I have not fully investigated this yet.
