### ISSUE TITLE
could pointnet2 work with python 3?

### ISSUE THREAD

**Issue by luodezhao** [charlesq34/pointnet2#79]
Hi， I'm really appreciate the nice work , but there are still some problems about 'print' when i'm trying to run it with python 3 .So do i have to modify the code?
Thank you !

**Comment by Bierfass** [comment]
Yes you have to modify all `print` and and replace `xrange` with `range`

**Comment by luodezhao** [comment]
@Bierfass Thank you !

**Comment by ruanhailiang** [comment]
Traceback (most recent call last):
  File "/home/emg/eclipse-workspace/pointnet2/scannet/train.py", line 18, in <module>
    from utils import pc_util
  File "/home/emg/eclipse-workspace/pointnet2/utils/pc_util.py", line 13, in <module>
    from eulerangles import euler2mat
ModuleNotFoundError: No module named 'eulerangles'
I 'm sorry, I cann't find the python module 'eulerangles' ?

**Comment by KosukeArase** [comment]
@ruanhailiang You can find it [here](https://github.com/charlesq34/pointnet/blob/master/utils/eulerangles.py)

**Comment by medif** [comment]
Hi,
I am using python3 but when i make train.py in scannet i got  error like 
line 17, in __init__
    self.scene_points_list = pickle.load(fp)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfc in position 1: ordinal not in range(128)

 did you  face S.TH like this

**Comment by zzusunquan** [comment]
> 追溯（最近一次通话）：
> 文件“ /home/emg/eclipse-workspace/pointnet2/scannet/train.py”，行18，
> 来自utils import pc_util 
> 文件“ / home / emg / eclipse-workspace / pointnet2 / utils /pc_util.py“，第13行，
> 从eulerangles导入euler2mat 
> ModuleNotFoundError：没有名为'eulerangles'的模块，
> 对不起，我找不到python模块'eulerangles'吗？

您好 请问您问题解决了嘛  我也需要了一样的问题

**Comment by houhaol** [comment]
> Hi,
> I am using python3 but when i make train.py in scannet i got error like
> line 17, in **init**
> self.scene_points_list = pickle.load(fp)
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xfc in position 1: ordinal not in range(128)
> 
> did you face S.TH like this

That's caused by python version. 
Replace pickle.load(fp, encoding='latin1') would help.

**Comment by hansen7** [comment]
> > Hi,
> > I am using python3 but when i make train.py in scannet i got error like
> > line 17, in **init**
> > self.scene_points_list = pickle.load(fp)
> > UnicodeDecodeError: 'ascii' codec can't decode byte 0xfc in position 1: ordinal not in range(128)
> > did you face S.TH like this
> 
> That's caused by python version.
> Replace pickle.load(fp, encoding='latin1') would help.

Hi @lianghouhao, that really helps, `pickle.load(fp, encoding='bytes')` works. But are the labels included in the pickle file?
